server:
  port: 8080 #端口
spring:
  application:
    name: api-zuul-server #服务名称
zuul:
  routes:
    #caonima:
      #path: /product-service/**
      #url: http://127.0.0.1:9001
      #serviceId: service-product
    service-product: /product-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
