server:
  port: 9112 #端口
spring:
  application:
    name: order-product #服务名称
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: http://127.0.0.1:9411/  #server的请求地址
    sender:
      type: web #数据的传输方式 , 已http的形式向server端发送数据
  sleuth:
    sampler:
      probability: 1 #采样比
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心中注册服务id
    lease-renewal-interval-in-seconds: 5 #向注册中心中注册服务id
    lease-expiration-duration-in-seconds: 10 #续约到期的时间


#配置feign日志的输出
#日志配置  NONE : 不输出日志(高)   BASIC: 适用于生产环境追踪问题
#HEADERS : 在BASIC的基础上,记录请求和响应头信息   FULL : 记录所有
feign:
  client:
    config:
      service-product:  #需要调用的服务名称
        loggerLevel: FULL
  hystrix:
    enabled: false
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ReadTimeout: 5000 # Ribbon的数据读取超时时间
  ConnectTimeout: 5000 # Ribbon的连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG